### ISSUE TITLE
解锁帧率迁移

### ISSUE THREAD

**Issue by Lightczx** [BlameTwo/GL#23]
看到了仓库使用了我们的
https://github.com/DGP-Studio/DGP.Genshin.FPSUnlocking
目前该仓库已经停止维护，请尽快迁移到
https://github.com/DGP-Studio/Unlocker
https://www.nuget.org/packages/Snap.Hutao.Service.Game.Unlocker

**Comment by BlameTwo** [comment]
已经寄了。
