### ISSUE TITLE
作者你好，我也在尝试学习用vs开发winui3的项目。但是我不知道怎么打包成exe的文件给别人用，我打包出来的是一堆dll文件和msix文件，这个问题让我很难受，你是怎么解决的

### ISSUE THREAD

**Issue by LanHuang025** [BlameTwo/GL#24]
作者你好，我也在尝试学习用vs开发winui3的项目。但是我不知道怎么打包成exe的文件给别人用，我打包出来的是一堆dll文件和msix文件，这个问题让我很难受，你是怎么解决的

**Comment by BlameTwo** [comment]
WinUI3是不能打包成单EXE的，他只能使用非打包模式做成exe+dll+依赖环境的

我比较推荐打包，因为打包后的文件体积小，其实也就几个msix有用。

**Comment by BlameTwo** [comment]
![image](https://user-images.githubusercontent.com/65759143/211975132-cae0f254-3207-43ba-9d9a-e38b0b32eb37.png)
