### ISSUE TITLE
打开主程序提示To run this application, you must install missing frameworks for .NET Would you like to download it now?

### ISSUE THREAD

**Issue by Utopia1916** [BlameTwo/GL#25]
打开之后弹窗提示“To run this application, you must install missing frameworks for .NET
Would you like to download it now?”，点击是之后并没有开始下载，我不知道去哪里下这个运行库

**Comment by BlameTwo** [comment]
这个运行库点击到跳转的地方即可，一般是.net–desktop版的runtime运行环境，.net6以上哦
